// Only for the Node test compiler; the deployed edge uses its actual Deno runtime.
declare global { var Deno:{env:{get:(name:string)=>string|undefined}}; }
import {describe,it,expect,vi,beforeEach} from 'vitest';
vi.mock('../../supabase/functions/nihongo-companion/service',()=>({ServiceError:class extends Error{constructor(public reason:string,public status=503){super(reason);}},jsonModel:vi.fn(),quota:vi.fn(),sign:vi.fn(async()=> 'a'.repeat(64)),validSignature:vi.fn(async()=>true),provider:vi.fn()}));
import {teacherLesson,teacherDemo} from '../../supabase/functions/nihongo-companion/teacher';
import {jsonModel,validSignature,provider} from '../../supabase/functions/nihongo-companion/service';
const subject={phrase:'少し休むつもりが、寝てしまいました。',meaningZh:'本来打算休息，结果睡着了。',kind:'explanation'};
const prepared={focus:'つもりが',scene:'休憩',cueZh:'本来想看五分钟，结果看了一小时。',keyword:'つもり',starter:'五分だけ見るつもりが、',exampleJa:'五分だけ見るつもりが、一時間見てしまいました。'};
const lesson={...prepared,subject,id:'lesson-001',signature:'f'.repeat(64)};
beforeEach(()=>{vi.clearAllMocks();vi.mocked(validSignature).mockResolvedValue(true);});
describe('server lesson and demonstration boundaries',()=>{
 it('rejects malformed requests before calling a model',async()=>{await expect(teacherLesson('unused',{input:{task:'prepare'}})).rejects.toThrow('invalid_teacher_input');expect(jsonModel).not.toHaveBeenCalled();});
 it('signs validated lessons rather than trusting a client assessment target',async()=>{vi.mocked(jsonModel).mockResolvedValue({text:JSON.stringify(prepared),data:{}});const r=await teacherLesson('unused',{callId:'rtc_test',input:{task:'prepare',requestId:'request-001',subject,previousScene:''}});expect(r.lesson?.signature).toBe('a'.repeat(64));expect(r.lesson?.subject).toEqual(subject);});
 it('rejects an unchanged scene when transfer was requested',async()=>{vi.mocked(jsonModel).mockResolvedValue({text:JSON.stringify(prepared),data:{}});await expect(teacherLesson('unused',{callId:'rtc_test',input:{task:'prepare',requestId:'request-001',subject,previousScene:'休憩'}})).rejects.toThrow('lesson_unavailable');});
 it('does not call the model on a tampered lesson',async()=>{vi.mocked(validSignature).mockResolvedValue(false);await expect(teacherLesson('unused',{callId:'rtc_test',input:{task:'assess',requestId:'attempt-001',lesson,answer:'見ていました。',support:0,source:'typed'}})).rejects.toThrow('invalid_lesson_signature');expect(jsonModel).not.toHaveBeenCalled();});
 it('keeps alternative phrasing distinct from target usage',async()=>{const assessment={verdict:'communicated',focusUsed:false,feedbackZh:'意思能表达出来，这次没有用到目标句型。',suggestionJa:''};vi.mocked(jsonModel).mockResolvedValue({text:JSON.stringify(assessment),data:{}});const r=await teacherLesson('unused',{callId:'rtc_test',input:{task:'assess',requestId:'attempt-001',lesson,answer:'長く見ました。',support:0,source:'typed'}});expect(r.assessment).toEqual(assessment);});
 it('invalid model JSON cannot be treated as progress',async()=>{vi.mocked(jsonModel).mockResolvedValue({text:'not json',data:{}});await expect(teacherLesson('unused',{callId:'rtc_test',input:{task:'assess',requestId:'attempt-001',lesson,answer:'長く見ました。',support:0,source:'typed'}})).rejects.toThrow('assessment_unavailable');});
 it('demonstrates the exact supplied text with fixed model, voice and natural speed',async()=>{vi.mocked(provider).mockResolvedValue(new Response(new Uint8Array(400)));const r=await teacherDemo('unused',{callId:'rtc_test',input:{text:subject.phrase,model:'untrusted'}});const body=JSON.parse(String(vi.mocked(provider).mock.calls[0][2].body));expect(body.input).toBe(subject.phrase);expect(body.speed).toBe(1);expect(body.model).toBe('gpt-4o-mini-tts');expect(body.voice).toBe('marin');expect(r.text).toBe(subject.phrase);});
 it('bounds paid demonstrations and does not accept arbitrary provider parameters',async()=>{await expect(teacherDemo('unused',{input:{text:'あ'.repeat(401)}})).rejects.toThrow('invalid_demo_input');expect(provider).not.toHaveBeenCalled();});
});
