import {describe,it,expect,vi,afterEach} from 'vitest';
vi.mock('../nhkAudioActivity',()=>({AudioActivityMeter:class{unlock(){}attach(){}detach(){}dispose(){}}}));
vi.mock('./api',()=>({companionApi:vi.fn(),sessionTicket:vi.fn(),stopSession:vi.fn(),fetchObservations:vi.fn()}));
import {CompanionConnection} from './connection';
import {freshPolicy,LOCAL_SEEDS,TranscriptLedger} from './model';
function setup(){vi.useFakeTimers();const events:any[]=[],hooks={phase:vi.fn(),lines:vi.fn(),activity:vi.fn(),notice:vi.fn(),error:vi.fn(),policy:vi.fn()};const c=new CompanionConnection(LOCAL_SEEDS[0],freshPolicy(),hooks),impl=c as any;impl.linked=true;impl.dc={readyState:'open',send:(s:string)=>events.push(JSON.parse(s)),close(){}};return{c,impl,events,hooks};}
afterEach(()=>{vi.useRealTimers();vi.clearAllMocks();});
describe('teacher update preserves the native conversation while making teaching explicit',()=>{
 it.each([1,.9,.7])('uses output speed 1 for pace preference %s',pace=>{const{c,events}=setup();c.setPace(pace);expect(events.at(-1).session.audio.output.speed).toBe(1);c.dispose();});
 it('a typed language question receives a real text response, not an empty audio promise',async()=>{const{c,events}=setup();c.sendText('这个词什么意思？');await vi.advanceTimersByTimeAsync(500);const r=events.find(e=>e.type==='response.create');expect(r.response.output_modalities).toEqual(['text']);expect(r.response).not.toHaveProperty('input');expect(r.response).not.toHaveProperty('conversation');c.dispose();});
 it('ordinary typed chat remains native audio',async()=>{const{c,events}=setup();c.sendText('今日は家でゆっくりしたいです。');await vi.advanceTimersByTimeAsync(500);expect(events.find(e=>e.type==='response.create').response.output_modalities).toEqual(['audio']);c.dispose();});
 it('speech still uses the original input item, not a synthetic transcription message',async()=>{const{c,impl,events}=setup();impl.lastInput='speech';impl.event({type:'input_audio_buffer.committed',item_id:'speech1'});impl.event({type:'conversation.item.input_audio_transcription.completed',item_id:'speech1',transcript:'つい是什么意思？'});await vi.advanceTimersByTimeAsync(1000);expect(events.find(e=>e.type==='response.create').response.output_modalities).toEqual(['audio']);expect(events.some(e=>e.type==='conversation.item.create')).toBe(false);c.dispose();});
 it('written-only teacher requests switch modalities but still use native conversation',async()=>{const{c,impl,events}=setup();c.setTeachingChannel('text');impl.event({type:'input_audio_buffer.committed',item_id:'speech1'});impl.event({type:'conversation.item.input_audio_transcription.completed',item_id:'speech1',transcript:'什么意思'});await vi.advanceTimersByTimeAsync(1000);expect(events.find(e=>e.type==='response.create').response.output_modalities).toEqual(['text']);c.dispose();});
 it('written-only with unavailable ASR is bounded and conservatively remains text',async()=>{const{c,impl,events}=setup();c.setTeachingChannel('text');impl.event({type:'input_audio_buffer.committed',item_id:'speech1'});await vi.advanceTimersByTimeAsync(2400);expect(events.find(e=>e.type==='response.create').response.output_modalities).toEqual(['text']);c.dispose();});
 it('finishes a text-only reply without waiting forever for an audio event',async()=>{const{c,impl,events,hooks}=setup();c.sendText('怎么说？');await vi.advanceTimersByTimeAsync(500);const r=events.find(e=>e.type==='response.create');impl.event({type:'response.created',response:{id:'r1',metadata:r.response.metadata}});impl.event({type:'response.output_item.added',response_id:'r1',item:{id:'a1',role:'assistant'}});impl.event({type:'response.output_text.done',response_id:'r1',item_id:'a1',text:'这句可以这样说。'});impl.event({type:'response.done',response:{id:'r1',status:'completed',output:[{id:'a1',role:'assistant',content:[{text:'这句可以这样说。'}]}]}});expect(hooks.phase).toHaveBeenLastCalledWith('ready');expect(c.lines.at(-1)?.textOnly).toBe(true);expect(c.lines.at(-1)?.delivered).toBe(true);c.dispose();});
 it('reading a note does not label an unrelated next utterance as assisted',()=>{const{c,impl}=setup();c.exposeNote('note1');c.useSupport('猫の動画が好きです。');expect(impl.supportFor('明日の午前に回答します。')).toBe('none');expect(impl.supportFor('猫の動画が好きです。')).toBe('example');impl.userTurns=3;expect(impl.supportFor('猫の動画が好きです。')).toBe('none');c.dispose();});
 it('isolated practice does not produce automatic competing voice responses',async()=>{const{c,impl,events}=setup();c.setPracticeMode(true);impl.event({type:'input_audio_buffer.committed',item_id:'practice1'});impl.event({type:'conversation.item.input_audio_transcription.completed',item_id:'practice1',transcript:'練習の答えです。'});await vi.advanceTimersByTimeAsync(1200);expect(events.some(e=>e.type==='response.create')).toBe(false);expect(c.lines[0].exercise).toBe(true);c.setPracticeMode(false);c.sendText('続けましょう。');await vi.advanceTimersByTimeAsync(500);expect(events.some(e=>e.type==='response.create')).toBe(true);c.dispose();});
 it('hypothetical exercise attempts are excluded from ordinary proficiency observation',()=>{const l=new TranscriptLedger();l.upsert('u1','user',{text:'自然な会話です。'});l.upsert('u2','user',{text:'練習の例です。',exercise:true});expect(l.evidence().map(e=>e.id)).toEqual(['u1']);});
});
