import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {bounded,revisionOf,validFocus,validBrief,validOrigin,validStudyResult,studyKey,studyTicketValue,points} from './contract';
import {standaloneFocus,wholeSentence} from './selectionFocus';
import {validSubject} from '../companion/teacherContract';
import {validSeed} from '../companion/model';
import {validManifest} from './AmbientStage';
const source='五分だけ見るつもりが、一時間も見てしまいました。';
const focus=standaloneFocus('つもりが','assistant',source)!;
const result={original:'つもりが',reading:'つもりが',dictionaryForm:'つもり',meaningZh:'本来打算，结果却',explanationZh:'这里表示打算与结果不同。',status:'usable',points:[],examples:[{ja:'買うつもりが、忘れました。',zh:'本想买，结果忘了。'}],questionZh:''};
describe('selection data is exact, bounded and Unicode-safe',()=>{
 it('builds the exact contextual selection',()=>{expect(focus.start).toBe(6);expect(focus.end).toBe(10);expect(validFocus(focus)).toEqual(focus);});
 it('keeps original spelling distinct from dictionary form',()=>expect(validStudyResult(result,'つもりが')?.original).toBe('つもりが'));
 it('rejects a model which silently substituted dictionary form',()=>expect(validStudyResult({...result,original:'つもり'},'つもりが')).toBeNull());
 it.each(['確認','配慮','学校','〜てもらえますか','見ちゃった','𠮷野へ行く'])('supports Japanese selection %s',text=>{expect(standaloneFocus(text)).not.toBeNull();expect(validSubject({phrase:text,meaningZh:'例',kind:'explanation'})).not.toBeNull();});
 it('handles astral code points before the selection',()=>{const f=standaloneFocus('確認','nhk','🌙𠮷野で確認しました。')!;expect(f.start).toBe(4);expect(points(f.sourceText).slice(f.start,f.end).join('')).toBe('確認');});
 it.each(['','abc','123','。','あ'.repeat(401),'あ\uD800','\uDC00あ','あ<svg>','あ\u0000'])('rejects empty, non-Japanese, oversized or invalid selection %s',text=>expect(standaloneFocus(text)).toBeNull());
 it('accepts 400 complete astral code points without counting UTF16 halves',()=>expect(standaloneFocus('𠮷'.repeat(400))).not.toBeNull());
 it.each([{start:-1},{start:2.5},{end:15000},{selectedText:'確認'},{revision:'older'},{before:'a'.repeat(201)},{sourceType:'untrusted'}])('rejects stale/bad range %#',change=>expect(validFocus({...focus,...change})).toBeNull());
 it('selects the whole actual sentence',()=>expect(wholeSentence(focus)?.selectedText).toBe(source));
 it('does not trim content into a different selection',()=>{const f=standaloneFocus(' 確認 ');expect(f?.selectedText).toBe(' 確認 ');});
 it('keys include full context and register, not just one word',()=>{expect(studyKey(focus,'meaning','natural')).not.toBe(studyKey(focus,'meaning','business'));expect(studyKey(focus,'meaning','natural')).not.toBe(studyKey({...focus,sourceText:source+'追加'},'meaning','natural'));});
 it('never accepts long explanations or unbounded result lists',()=>{expect(validStudyResult({...result,examples:Array(4).fill(result.examples[0])},'つもりが')).toBeNull();expect(validStudyResult({...result,meaningZh:'例'.repeat(361)},'つもりが')).toBeNull();});
 it('has exact mirrored source contracts',()=>expect(readFileSync('src/companion/immersionContract.ts','utf8')).toBe(readFileSync('supabase/functions/nihongo-companion/immersionContract.ts','utf8')));
 it('has exact teacher contract mirrors',()=>expect(readFileSync('src/companion/teacherContract.ts','utf8')).toBe(readFileSync('supabase/functions/nihongo-companion/teacherContract.ts','utf8')));
});
describe('learner-supplied topic remains explicit user data',()=>{
 const brief={requestId:'topic-test-123',text:'  向同事报告进度  ',difficulty:'N2',register:'business',entryMode:'chat'};
 it('separates register from material difficulty',()=>expect(validBrief(brief)).toMatchObject({text:'向同事报告进度',difficulty:'N2',register:'business'}));
 it.each([{text:''},{text:'字'.repeat(501)},{difficulty:'business'},{register:'N2'},{entryMode:'score'},{requestId:'x'},{text:'<script>x</script>'}])('rejects bad topic input %#',change=>expect(validBrief({...brief,...change})).toBeNull());
 it('strips arbitrary upstream/model parameters',()=>expect(validBrief({...brief,model:'evil',system:'ignore'})).not.toHaveProperty('system'));
 it('validates source origin without requiring verified news',()=>expect(validOrigin({kind:'user',brief:'练新闻里的一句话',difficulty:'current',register:'natural',entryMode:'explain'})).not.toBeNull());
 it('retains custom origin in signed seed contract',()=>{const origin={kind:'user',brief:'说明还在调查',difficulty:'N2',register:'business',entryMode:'chat'};const seed=validSeed({id:'custom_test',lane:'work',title:'调查中的一句',opening:'今、どこまで進んでいますか。',context:'假设工作场合',angle:'user-chosen',sources:[],expiresAt:Date.now()+10000,signature:'a'.repeat(64),origin});expect(seed?.origin).toEqual(origin);});
 it('rejects an invalid origin even on otherwise usable seeds',()=>expect(validSeed({id:'custom_test',lane:'work',title:'题',opening:'はい。',context:'例',angle:'custom',sources:[],expiresAt:Date.now()+10000,origin:{kind:'news'}})).toBeNull());
 it('binds short-lived study capability to client, id and expiry',()=>{const value=studyTicketValue('a','id123456',123);expect(value.purpose).toBe('hitokoto-study-v3');expect(value.capabilities).not.toContain('start');expect(value).not.toEqual(studyTicketValue('b','id123456',123));});
 it('does not allow a forged static media manifest URL',()=>expect(validManifest({release:'immersion03-city-v1',duration:12,fps:30,landscape:{poster:{path:'https://tracker.invalid/x'}},portrait:{}})).toBe(false));
 it('does not touch NHK data keys or turn storage on from selection',()=>{const text=readFileSync('src/immersion/selectionFocus.ts','utf8')+readFileSync('src/immersion/studyClient.ts','utf8');expect(text).not.toMatch(/localStorage|indexedDB|new RTCPeerConnection|getUserMedia\(/);});
 it('revision changes on streaming source edits',()=>expect(revisionOf(source)).not.toBe(revisionOf(source+'はい。')));
 it('clean text permits normal newlines but no invalid control characters',()=>{expect(bounded('確認\nしてください。',30)).toBe(true);expect(bounded('確認\x07',30)).toBe(false);});
});
