/** Cat/audio acceptance in a real foreground Chrome viewport. No FPS benchmark. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { recordBrowser } from './record-browser.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
const out=path.join(root,'docs/living-scene/cat-v1/evidence');
const capture=process.env.CAPTURE_DIR || '/Users/xiaruonan/nihongo-art-work/toolchain/cat-v1-capture';
await fs.mkdir(out,{recursive:true});
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || '/Users/xiaruonan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:false,args:['--use-angle=metal','--disable-backgrounding-occluded-windows']});
const p=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});
const errors=[],checks={},states={};
p.on('pageerror',e=>errors.push(String(e)));
p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
p.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const snap=()=>p.evaluate(()=>{const s=window.__livingScene.snapshot();return {cat:s.cat,audio:s.audio,story:s.story,paused:s.paused,time:s.time,errors:s.errors};});
const shot=n=>p.screenshot({path:path.join(out,`${n}.png`)});
const edge=()=>p.mouse.move(1880,1070);
const check=(name,value)=>{checks[name]=value;assert(value,name);};
try {
  await p.bringToFront();
  await p.goto(process.env.SCENE_URL || 'http://127.0.0.1:8774/?qa=1');
  await p.waitForFunction(()=>window.__livingScene?.ready);
  states.initial=await snap();
  check('defaultNoAutoplay',!states.initial.audio.enabled && states.initial.audio.state==='uninitialized');
  await p.mouse.move(800,450);await p.waitForTimeout(6200);await shot('hero-clean');
  check('catReady',states.initial.cat.ready);
  await p.locator('#cat-hotspot').hover();await p.waitForTimeout(150);
  check('hoverReaction',(await snap()).cat.ear>0);
  await p.locator('#cat-hotspot').click();await p.waitForTimeout(1300);
  states.attentive=await snap();check('clickHeadLift',states.attentive.cat.state==='attentive' && states.attentive.cat.pose>.9);
  check('explanationOptIn',await p.locator('#cat-explanation').isHidden());
  await shot('cat-attentive');
  await edge();await p.locator('#sound').click();await p.waitForTimeout(1800);
  states.audioOn=await snap();check('userGestureAudio',states.audioOn.audio.enabled && states.audioOn.audio.state==='running');
  await p.locator('#cat-pet').click();await p.waitForTimeout(1800);
  states.purring=await snap();check('petClosedEyes',states.purring.cat.state==='purring' && states.purring.cat.content>.9);
  check('purrDucksMusic',states.purring.audio.buses.music<states.audioOn.audio.buses.music && states.purring.audio.buses.purr>.28);
  await p.locator('#cat-explain').click();check('catExplanation',await p.locator('#cat-explanation').isVisible());await shot('cat-purring');
  await p.locator('#cat-look').click();await p.waitForTimeout(1300);
  states.watching=await snap();check('lookTowardBranch',states.watching.cat.state==='watching' && states.watching.cat.gaze<-.8);await shot('cat-watching');
  await p.locator('#cat-rest').click();await p.waitForTimeout(1300);
  states.sleeping=await snap();check('restClosedEyes',states.sleeping.cat.state==='sleeping' && states.sleeping.cat.content>.9);await shot('cat-resting');
  await p.keyboard.press('Escape');
  check('escapeReturnsToCat',await p.evaluate(()=>document.activeElement.id==='cat-hotspot' && document.querySelector('#cat-panel').hidden && !document.querySelector('#hotspots').inert));
  const r=await p.locator('#cat-hotspot').boundingBox();
  await p.mouse.move(r.x+r.width*.30,r.y+r.height*.53);await p.mouse.down();await p.waitForTimeout(900);await p.mouse.up();
  check('directChinHold',(await snap()).cat.state==='purring');
  await p.keyboard.press('Escape');
  await p.locator('#hotspot-shop').click();check('existingShopOpens',(await snap()).story.active==='shop');
  await p.locator('#choices button').first().click();await p.locator('#next').click();
  await p.locator('#choices button').first().click();await p.locator('#next').click();
  check('ownerIntroducesCat',await p.locator('#story-line').textContent().then(s=>s.includes('ラテ')));await shot('owner-cat');
  await p.keyboard.press('Escape');
  await edge();await p.locator('#pause').click();const frozen=await snap();await p.waitForTimeout(450);
  const paused=await snap();check('pauseFreezesCat',paused.cat.elapsed===frozen.cat.elapsed && paused.time===frozen.time);
  await p.locator('#pause').click();await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(400);
  check('reducedMotion',(await snap()).paused);await p.emulateMedia({reducedMotion:'no-preference'});
  await edge();await p.locator('#sound').click();check('muteButton',!(await snap()).audio.enabled);
  const remembered=(await snap()).cat;
  await p.evaluate(()=>localStorage.setItem('cat-qa-unrelated','preserve-me'));
  await p.reload();await p.waitForFunction(()=>window.__livingScene?.ready);
  states.revisit=await snap();
  check('revisitOtherAnchor',states.revisit.cat.anchorIndex!==remembered.anchorIndex);
  check('touchesPersist',states.revisit.cat.touches===remembered.touches);
  check('unrelatedStoragePreserved',await p.evaluate(()=>localStorage.getItem('cat-qa-unrelated')==='preserve-me'));
  await p.locator('#cat-hotspot').click();check('familiarGreeting',await p.locator('#cat-line').textContent().then(s=>s.includes('また')));
  await p.keyboard.press('Escape');await p.mouse.move(800,450);await p.locator('#cat-hotspot').blur();
  console.log('Interaction/audio checks passed; observing automatic idle rest.');
  await p.waitForFunction(()=>window.__livingScene.snapshot().cat.state==='sleeping',{},{timeout:60000});
  states.idle=await snap();check('automaticIdleRest',states.idle.cat.state==='sleeping' && !states.idle.cat.active);await shot('idle-other-anchor');
  const recording=await recordBrowser(p,capture,async page=>{
    await page.mouse.move(1550,890);await page.locator('#sound').click();
    await page.evaluate(()=>{
      const stream=window.__livingAudioCapture();const chunks=[];
      window.catRecording=new MediaRecorder(stream,{mimeType:'audio/webm;codecs=opus'});
      window.catRecording.ondataavailable=e=>chunks.push(e.data);
      window.catAudioDone=new Promise(resolve=>window.catRecording.onstop=async()=>{
        const b=new Uint8Array(await new Blob(chunks).arrayBuffer());
        let binary='';for(let i=0;i<b.length;i++)binary+=String.fromCharCode(b[i]);resolve(btoa(binary));
      });
      window.catAudioStart=Date.now()/1000;window.catRecording.start();
    });
    await page.mouse.move(800,440);await page.waitForTimeout(3500);
    await page.locator('#cat-hotspot').hover();await page.waitForTimeout(1600);
    await page.locator('#cat-hotspot').click();await page.waitForTimeout(3200);
    await page.locator('#cat-pet').click();await page.waitForTimeout(4800);
    await page.locator('#cat-look').click();await page.waitForTimeout(4000);
    await page.locator('#cat-rest').click();await page.waitForTimeout(4500);
    await page.keyboard.press('Escape');await page.mouse.move(750,450);await page.waitForTimeout(3500);
    await page.evaluate(()=>window.catRecording.stop());
  });
  const b64=await p.evaluate(()=>window.catAudioDone);await fs.writeFile(path.join(out,'scene-audio.webm'),Buffer.from(b64,'base64'));
  const audio=await p.evaluate(async b64=>{
    const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const ctx=new AudioContext();
    const buffer=await ctx.decodeAudioData(bytes.buffer);let sum=0,peak=0;
    const channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i));
    for(const ch of channels)for(const v of ch){peak=Math.max(peak,Math.abs(v));sum+=v*v;}
    const wav=new ArrayBuffer(44+buffer.length*channels.length*2),view=new DataView(wav);
    const str=(offset,text)=>[...text].forEach((c,i)=>view.setUint8(offset+i,c.charCodeAt(0)));
    str(0,'RIFF');view.setUint32(4,wav.byteLength-8,true);str(8,'WAVE');str(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels.length,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels.length*2,true);view.setUint16(32,channels.length*2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,wav.byteLength-44,true);
    for(let i=0;i<buffer.length;i++)for(let c=0;c<channels.length;c++)view.setInt16(44+(i*channels.length+c)*2,Math.round(Math.max(-1,Math.min(1,channels[c][i]))*32767),true);
    let binary='';for(const n of new Uint8Array(wav))binary+=String.fromCharCode(n);
    await ctx.close();return {duration:buffer.duration,sampleRate:buffer.sampleRate,channels:channels.length,peak,rms:Math.sqrt(sum/(buffer.length*channels.length)),started:window.catAudioStart,wav:btoa(binary)};
  },b64);
  await fs.writeFile(path.join(capture,'scene-audio.wav'),Buffer.from(audio.wav,'base64'));delete audio.wav;
  const frames=JSON.parse(await fs.readFile(path.join(capture,'timestamps.json'),'utf8'));
  audio.offsetSeconds=audio.started-frames[0].timestamp;
  check('actualAudioNotSilent',audio.rms>.0001 && audio.peak<.99);
  await fs.writeFile(path.join(capture,'audio-timing.json'),JSON.stringify(audio,null,2));
  check('noBrowserErrors',errors.length===0);
  const hardware=await p.evaluate(()=>window.__livingScene.hardware);
  await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify({date:new Date().toISOString(),url:p.url(),checks,states,errors,hardware,recording,audio,performance:'Not benchmarked; per user direction.'},null,2));
  console.log(JSON.stringify({checks,recording,audio,errors},null,2));
} catch(error) {
  states.failureCurrent=await snap();states.visibility=await p.evaluate(()=>document.visibilityState);await shot('failure');await fs.writeFile(path.join(out,'browser-failure.json'),JSON.stringify({checks,states,errors,failure:String(error)},null,2));throw error;
} finally {await browser.close();}
