import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..');
const out=path.join(root,'docs/living-scene/chapter1-v1/evidence');
await fs.mkdir(out,{recursive:true});
const {chromium}=await import('/Users/xiaruonan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:false,args:['--use-angle=metal','--disable-backgrounding-occluded-windows']});
const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1});
const checks={}, errors=[];
page.on('pageerror',e=>errors.push(String(e)));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const snap=()=>page.evaluate(()=>window.__chapter.snapshot());
const room=async id=>{await page.waitForFunction(id=>window.__chapter.snapshot().room===id&&!window.__chapter.snapshot().busy,id);await page.waitForTimeout(450);};
const edge=()=>page.mouse.move(1000,1075);
const shot=name=>page.screenshot({path:path.join(out,name+'.png')});
const ok=(name,value)=>{checks[name]=!!value;assert(value,name);};
const talk=()=>page.locator('#room-hotspot').click();
const next=async()=>{await edge();await page.locator('#room-next').click();};
try{
 await page.goto(process.env.SCENE_URL||'http://127.0.0.1:8781/?qa=1');
 await page.waitForFunction(()=>window.__livingScene?.ready);
 await page.waitForTimeout(1200);
 ok('fiveOriginalHotspots',await page.locator('#hotspots button').count()===5);
 await page.locator('#hotspot-shop').click();await page.locator('#story-enter').click();await room('shop');
 await page.mouse.move(850,400);await page.waitForTimeout(6000);await shot('shop-clean');
 const t=(await snap()).motion.elapsed;await page.waitForTimeout(500);
 ok('interiorAnimationAdvances',(await snap()).motion.elapsed>t+.2);
 await talk();ok('translationOptIn',await page.locator('#room-translation').isHidden());
 await page.locator('#room-explain').click();ok('translationVisible',await page.locator('#room-translation').isVisible());
 await page.locator('#room-choices button').first().click();ok('dinnerReserved',(await snap()).ordered);
 await shot('shop-promise');
 await page.locator('#room-choices button').first().click();await room('sento');
 await page.mouse.move(850,400);await page.waitForTimeout(6000);await shot('sento-clean');
 await talk();await page.locator('#room-choices button').first().click();await room('bath');
 await page.mouse.move(850,400);await page.waitForTimeout(6000);await shot('bath-clean');
 // Compare the same view over time: evidence of actual shader movement, no camera movement.
 await page.waitForTimeout(2100);await shot('bath-motion-later');
 await edge();await page.locator('#pause').click();
 const stopped=(await snap()).motion.elapsed;await page.waitForTimeout(500);ok('pauseStopsInteriors',(await snap()).motion.elapsed===stopped);
 await page.locator('#pause').click();await page.emulateMedia({reducedMotion:'reduce'});
 const reduced=(await snap()).motion.elapsed;await page.waitForTimeout(350);ok('reducedMotionStopsInteriors',(await snap()).motion.elapsed===reduced);
 await page.emulateMedia({reducedMotion:'no-preference'});
 await talk();await page.locator('#room-choices button').first().click();ok('bathingRemembered',(await snap()).bathed);
 await page.locator('#room-explain').click();await shot('bath-return-thought');
 await page.locator('#room-choices button').first().click();await room('sento');await next();await room('shop');
 await talk();ok('ownerRemembersPromise',(await snap()).dialogue.includes('約束のお弁当'));
 await shot('shop-return');await page.locator('#room-choices button').first().click();ok('dinnerCollected',(await snap()).collected);
 await page.keyboard.press('Escape');ok('escapeFirstHidesDialogue',!(await snap()).dialogue);
 await page.keyboard.press('Escape');await room('street');
 ok('catStaysInStreet',await page.locator('#cat-hotspot').isVisible());
 const state=await page.evaluate(()=>window.__livingScene.snapshot());
 await page.reload();await page.waitForFunction(()=>window.__livingScene?.ready);ok('chapterSurvivesRefresh',(await snap()).collected);
 // Only this new chapter test key is cleared; pre-existing user schemas are untouched.
 await page.evaluate(()=>sessionStorage.removeItem('livingScene.chapter1.v1'));
 await page.reload();await page.waitForFunction(()=>window.__livingScene?.ready);
 await edge();await page.locator('#places-toggle').click();await page.locator('#enter-sento').click();await room('sento');await next();await room('bath');await talk();
 await page.locator('#room-choices button').first().click();await page.keyboard.press('Escape');await next();await room('sento');await next();await room('shop');await talk();
 ok('bathFirstDoesNotInventOrder',!(await snap()).ordered&&(await snap()).dialogue.includes('晩ごはん'));
 await page.keyboard.press('Escape');await page.keyboard.press('Escape');await room('street');
 // Sound starts only after a real user gesture; interior buses use the same context.
 await edge();await page.locator('#sound').click();await page.waitForTimeout(450);
 ok('audioEnabled',await page.evaluate(()=>window.__livingScene.snapshot().audio.enabled));
 await page.locator('#hotspot-shop').click();await page.locator('#story-enter').click();await room('shop');await page.waitForTimeout(1000);
 ok('catBusQuietIndoors',await page.evaluate(()=>window.__livingScene.snapshot().audio.buses.cat<.01));
 await page.keyboard.press('Escape');await room('street');await page.waitForTimeout(1000);
 ok('catBusReturnsOutside',await page.evaluate(()=>window.__livingScene.snapshot().audio.buses.cat>.09));
 ok('noBrowserErrors',errors.length===0);
 await fs.writeFile(path.join(out,'browser-check.json'),JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),hardware:await page.evaluate(()=>window.__livingScene.hardware),viewport:[1920,1080],checks,errors,catDefaultSourceWidth:.045,scope:'Chapter continuity, region animation, controls and audio routing. No FPS optimization or NHK tests.'},null,2));
 console.log(JSON.stringify(checks,null,2));
}finally{await browser.close();}
