import {chromium,webkit} from 'playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.CITY05_BASE||'http://127.0.0.1:4173',out=process.env.CITY05_OUT||'artifacts/city05-browser';await mkdir(out,{recursive:true});
const report={ok:false,base,scope:'REAL_HOSTED_ARTWORK_REAL_CANVAS_AND_MUSIC_DECODING_MOCKED_VOICE_AND_TEACHER_NO_PHYSICAL_DEVICE',cases:[],errors:[],stage:'start'};let browser,page;
try{
 for(const engine of (process.env.CITY05_ENGINES||'chromium,webkit').split(','))for(const viewport of [{width:1536,height:960},{width:390,height:844}]){
  report.stage=engine+'-'+viewport.width+': setup';browser=await({chromium,webkit})[engine].launch({headless:true});const context=await browser.newContext({viewport,hasTouch:viewport.width<600,isMobile:viewport.width<600,reducedMotion:'no-preference',serviceWorkers:'block'});page=await context.newPage();page.setDefaultTimeout(25000);
  const mp3Requests=[];page.on('request',r=>{if(/\/city05\/.*\.mp3/.test(r.url()))mp3Requests.push(r.url());});page.on('pageerror',e=>report.errors.push({engine,width:viewport.width,message:e.message}));
  await page.addInitScript(()=>{
   window.__city05={peers:0,mic:0,events:[],dc:null,tracks:[],music:[],musicPlays:0};const state=window.__city05;localStorage.setItem('city05-preserve-probe','KEEP');
   const original=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){if(this.dataset.cityMusic==='true'){state.musicPlays++;if(!state.music.includes(this))state.music.push(this);}return original.apply(this,args);};
   Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>{state.mic++;const t={enabled:true,readyState:'live',muted:false,stop(){this.readyState='ended';}};state.tracks.push(t);return{getTracks:()=>[t],getAudioTracks:()=>[t]};}}});
   window.RTCPeerConnection=class{connectionState='connected';localDescription=null;constructor(){state.peers++;}addTransceiver(){return{sender:{replaceTrack:async()=>{}}};}createDataChannel(){return state.dc={readyState:'connecting',send:s=>state.events.push(JSON.parse(s)),close(){},onopen:null,onmessage:null};}async createOffer(){return{type:'offer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n'};}async setLocalDescription(s){this.localDescription=s;}async setRemoteDescription(){state.dc.readyState='open';state.dc.onopen?.();}close(){}};
  });
  await page.route('**/api/nhk-speech',async route=>{const b=route.request().postDataJSON();if(b.action==='companion_start')return route.fulfill({json:{ok:true,contract:'nihongo-companion-v3',model:'gpt-realtime-2.1',sdp:'v=0',callId:'rtc_city05_fixture',expiresAt:Date.now()+1200000,token:'a'.repeat(64)}});if(b.action==='companion_feedback'){const i=b.input;return route.fulfill({json:{ok:true,note:{id:i.requestId,anchorId:i.anchorId,source:i.source,mode:i.mode,kind:'extension',certainty:'clear',meaningPreserved:true,suggestion:'もう一度確認します。',reasonZh:'可以这样接一句，不是原句错误。',detailZh:''}}});}return route.fulfill({json:{ok:true,topics:[],observations:[]}});});
  const reply=async text=>page.evaluate(text=>{const v=window.__city05,req=v.events.filter(e=>e.type==='response.create').at(-1),id='r'+req.response.metadata.seq,item='a'+id,emit=e=>v.dc.onmessage({data:JSON.stringify(e)});emit({type:'response.created',response:{id,metadata:req.response.metadata}});emit({type:'response.output_item.added',response_id:id,item:{id:item,role:'assistant',type:'message'}});document.querySelector('audio').onplaying?.();emit({type:'output_audio_buffer.started',response_id:id});emit({type:'response.output_audio_transcript.done',response_id:id,item_id:item,transcript:text});emit({type:'response.done',response:{id,status:'completed',output:[{id:item,role:'assistant',content:[{transcript:text}]}]}});emit({type:'output_audio_buffer.stopped',response_id:id});},text);
  await page.goto(base+'/',{waitUntil:'domcontentloaded'});await page.locator('[data-city-release="city-20260911-v5"]').waitFor();assert.equal(new URL(page.url()).pathname,'/companion.html');
  await page.waitForFunction(()=>document.querySelector('.c05-stage')?.dataset.renderedScene==='skyport'&&Number(document.querySelector('.c05-stage canvas')?.dataset.frames)>2);
  assert.equal(mp3Requests.length,0,'Music must not download before opt-in');assert.equal(await page.evaluate(()=>window.__city05.mic),0);
  await page.getByRole('button',{name:'聊一会儿',exact:true}).click();await page.waitForFunction(()=>window.__city05.events.some(e=>e.type==='response.create'));await reply('空に浮かぶ車が見えますね。');
  const snap=()=>page.locator('.c05-stage canvas').evaluate(c=>{const sample=document.createElement('canvas');sample.width=100;sample.height=100;const x=sample.getContext('2d');x.drawImage(c,0,0,100,100);return{frames:Number(c.dataset.frames),flightX:c.dataset.flightX,flightY:c.dataset.flightY,screen:c.dataset.screenPage,train:c.dataset.trainPosition,scene:c.dataset.scene,pixels:Array.from(x.getImageData(0,0,100,100).data)};});
  const first=await snap();await page.waitForTimeout(1400);const second=await snap();assert.ok(second.frames>first.frames);assert.notDeepEqual(second.pixels,first.pixels,'Painted scenery must really change');assert.ok(Number.isFinite(Number(second.flightX)));assert.notEqual(second.train,first.train);
  await page.getByRole('button',{name:'风景',exact:true}).click();await page.locator('.c05-picker').waitFor();assert.equal(await page.locator('.c05-scene-grid>button').count(),4);
  const scenes=[];
  for(const id of ['skyport','canyon','harbor','rail']){
   await page.locator(`[data-scene-choice="${id}"]`).click();await page.waitForFunction(id=>document.querySelector('.c05-stage')?.dataset.renderedScene===id,id);
   const a=await snap();await page.waitForTimeout(450);const b=await snap();assert.ok(b.frames>a.frames);assert.equal(await page.evaluate(()=>window.__city05.peers),1);assert.equal(await page.evaluate(()=>window.__city05.mic),0);
   scenes.push(id);await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.screenshot({path:`${out}/${engine}-${viewport.width}-${id}.png`,fullPage:true});await page.getByRole('button',{name:'风景',exact:true}).click();
  }
  await page.locator('[data-scene-choice="skyport"]').click();await page.locator('[data-scene-choice="harbor"]').click();await page.waitForFunction(()=>document.querySelector('.c05-stage')?.dataset.renderedScene==='harbor');await page.waitForTimeout(350);assert.equal(await page.locator('.c05-stage').getAttribute('data-rendered-scene'),'harbor');
  await page.getByRole('button',{name:'减少动态，保留高清静帧',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.c05-stage canvas')?.dataset.running==='false');let a=await snap();await page.waitForTimeout(300);assert.equal((await snap()).frames,a.frames);await page.getByRole('button',{name:'启用动态风景与粒子',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.c05-stage canvas')?.dataset.running==='true');
  report.stage=engine+'-'+viewport.width+': actual music decoding';
  await page.locator('dialog').getByRole('button',{name:'开启背景音乐',exact:true}).click();await page.waitForFunction(()=>window.__city05.music.length===1&&window.__city05.music[0].currentTime>.15&&!window.__city05.music[0].paused);await page.waitForFunction(()=>window.__city05.music[0].volume>.10);
  await page.getByRole('slider',{name:'背景音乐音量'}).focus();await page.getByRole('slider',{name:'背景音乐音量'}).press('Home');await page.waitForFunction(()=>window.__city05.music[0].volume===0);await page.getByRole('slider',{name:'背景音乐音量'}).press('End');
  await page.getByRole('button',{name:'关闭面板',exact:true}).click();await page.getByRole('button',{name:'开启麦克风',exact:true}).click();await page.waitForFunction(()=>window.__city05.mic===1);await page.waitForFunction(()=>window.__city05.music[0].volume===0);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.__city05.music[0].volume),0);
  await page.getByRole('button',{name:'关闭麦克风',exact:true}).click();await page.waitForFunction(()=>window.__city05.music[0].volume>.05);
  await page.evaluate(()=>window.__city05.dc.onmessage({data:JSON.stringify({type:'output_audio_buffer.started'})}));await page.waitForTimeout(600);assert.ok(await page.evaluate(()=>window.__city05.music[0].volume<.065));await page.evaluate(()=>window.__city05.dc.onmessage({data:JSON.stringify({type:'output_audio_buffer.stopped'})}));
  await page.getByRole('button',{name:'关闭背景音乐',exact:true}).click();assert.equal(await page.evaluate(()=>window.__city05.music[0].paused),true);
  await page.getByRole('button',{name:'接不上',exact:true}).click();await page.locator(viewport.width>=1100?'.df-current-note .kc-note-japanese':'.kc-written-note').waitFor();assert.equal(await page.evaluate(()=>window.__city05.peers),1);if(viewport.width>=1100)assert.equal(await page.locator('.df-teacher').count(),1);
  const mic=await page.getByRole('button',{name:'开启麦克风',exact:true}).boundingBox();assert.ok(mic&&mic.y>=0&&mic.y+mic.height<=viewport.height+1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.c05-stage canvas')?.dataset.running==='false');a=await snap();await page.waitForTimeout(350);assert.equal((await snap()).frames,a.frames);
  assert.equal(await page.evaluate(()=>window.__city05.music.length),1);assert.ok(await page.evaluate(()=>window.__city05.tracks.every(t=>t.readyState==='ended')));assert.equal(await page.evaluate(()=>localStorage.getItem('city05-preserve-probe')),'KEEP');
  const music=await page.evaluate(()=>({duration:window.__city05.music[0].duration,src:window.__city05.music[0].src,paused:window.__city05.music[0].paused}));assert.ok(music.duration>40&&music.duration<60);
  report.cases.push({engine,viewport,scenes,actualMovingPixels:true,independentFlightTrainAndScreens:true,rapidSwitchLatestWins:true,musicOptInAndDecoded:true,musicDuration:music.duration,micHardMute:true,voiceDucking:true,zeroVolumeSilent:true,oneMusicPlayer:true,teacherStillVisible:true,oneNativeVoicePeer:true,reducedMotionStopsFrames:true,normalRootEntry:true,artwork:'Native crops, not native4K',pageErrors:[]});await context.close();await browser.close();browser=null;
 }
 assert.deepEqual(report.errors,[]);report.ok=true;report.stage='complete';
}catch(e){report.failure=String(e.stack||e);process.exitCode=1;if(page&&!page.isClosed()){await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});await writeFile(out+'/failure.html',await page.content()).catch(()=>{});}}finally{await browser?.close();await writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log('CITY05_BROWSER',JSON.stringify(report));}
