import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {NhkChatConnection} from './nhkChatConnection';
import {buildChatPlan,chatTopics} from './nhkChat';
const plan=buildChatPlan({id:'test',title:'SNS',sentences:['SNSやスマートフォンを使います。']});
let dc:any,track:any,hooks:any,c:NhkChatConnection,peer:any,replyNumber=0;
const emit=(e:any)=>dc.onmessage?.({data:JSON.stringify(e)});
function reply(){const id=`r${++replyNumber}`;emit({type:'response.created',response:{id}});emit({type:'response.output_audio_transcript.done',response_id:id,transcript:'そうなんですね。猫は好きですか。'});emit({type:'output_audio_buffer.started',response_id:id});emit({type:'response.done',response:{id,status:'completed'}});emit({type:'output_audio_buffer.stopped',response_id:id});}
const speak=(id:string,text:string)=>{emit({type:'input_audio_buffer.speech_started'});emit({type:'input_audio_buffer.speech_stopped'});emit({type:'input_audio_buffer.committed',item_id:id});emit({type:'conversation.item.input_audio_transcription.completed',item_id:id,transcript:text});};
const starts=()=>((fetch as any).mock.calls as any[]).filter(v=>JSON.parse(v[1].body).action==='speaking_start');
beforeEach(()=>{vi.useFakeTimers();replyNumber=0;track={enabled:true,stop:vi.fn()};const stream={getTracks:()=>[track],getAudioTracks:()=>[track]};vi.stubGlobal('window',{isSecureContext:true});vi.stubGlobal('navigator',{mediaDevices:{getUserMedia:vi.fn().mockResolvedValue(stream)}});vi.stubGlobal('document',{body:{appendChild:vi.fn()},createElement:()=>({style:{},setAttribute:vi.fn(),play:vi.fn().mockResolvedValue(undefined),pause:vi.fn(),remove:vi.fn()})});
class Peer{connectionState='connected';localDescription:any;ontrack:any;onconnectionstatechange:any;constructor(){peer=this;}addTrack(){}createDataChannel(){dc={readyState:'connecting',send:vi.fn(),close:vi.fn(),onmessage:null,onclose:null,onopen:null,onerror:null};return dc;}async createOffer(){return{type:'offer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n'};}async setLocalDescription(v:any){this.localDescription=v;}async setRemoteDescription(){dc.readyState='open';dc.onopen?.();}close=vi.fn();}
vi.stubGlobal('RTCPeerConnection',Peer);vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>new Response(JSON.stringify({ok:true,chatContract:'nhk-chat-v2',contractVersion:'nhk-speaking-v1',model:'gpt-realtime-2.1',sdp:'v=0',callId:'rtc_test',expiresAt:Date.now()+110000,stopToken:'a'.repeat(64)}))));hooks={phase:vi.fn(),assistant:vi.fn(),hint:vi.fn(),blocked:vi.fn(),error:vi.fn(),shuffle:vi.fn(),heard:vi.fn()};c=new NhkChatConnection(plan,hooks);});
afterEach(()=>{c.dispose();vi.useRealTimers();vi.unstubAllGlobals();});
describe('continuous mobile topic chat lifecycle',()=>{
 it('never opens a microphone before start',()=>expect(navigator.mediaDevices.getUserMedia).not.toHaveBeenCalled());
 it('continues beyond three answers including yes/no',async()=>{await c.start();reply();for(let i=0;i<5;i++){speak(String(i),'はい');reply();}expect(hooks.heard).toHaveBeenCalledTimes(5);expect(track.stop).not.toHaveBeenCalled();expect(starts()).toHaveLength(1);});
 it('shuffles repeatedly without reconnecting or reopening microphone',async()=>{await c.start();reply();for(let i=0;i<20;i++)c.changeTopic({...plan,topicId:chatTopics(plan)[i%chatTopics(plan).length].id});await vi.advanceTimersByTimeAsync(450);reply();expect(starts()).toHaveLength(1);expect(navigator.mediaDevices.getUserMedia).toHaveBeenCalledTimes(1);});
 it('excludes late transcript from the old topic',async()=>{await c.start();reply();emit({type:'input_audio_buffer.committed',item_id:'old'});c.changeTopic({...plan,topicId:chatTopics(plan)[1].id});await vi.advanceTimersByTimeAsync(450);reply();emit({type:'conversation.item.input_audio_transcription.completed',item_id:'old',transcript:'wrong topic'});expect(hooks.heard).not.toHaveBeenCalled();});
 it('help follows the latest question, not the original script',async()=>{await c.start();reply();speak('one','猫が好きです');reply();c.help();const event=JSON.parse(dc.send.mock.calls.at(-1)[0]);expect(event.response.instructions).toContain('猫は好きですか');expect(event.response.instructions).toContain('MOST RECENT');});
 it('waits for playback end before passing microphone audio',async()=>{await c.start();emit({type:'response.created',response:{id:'x'}});emit({type:'response.done',response:{id:'x',status:'completed'}});expect(track.enabled).toBe(false);emit({type:'output_audio_buffer.stopped',response_id:'x'});expect(track.enabled).toBe(true);});
 it('renews a transport lease without asking for microphone permission again',async()=>{await c.start();reply();await vi.advanceTimersByTimeAsync(45000);speak('one','猫');reply();await vi.advanceTimersByTimeAsync(41000);expect(starts()).toHaveLength(2);expect(navigator.mediaDevices.getUserMedia).toHaveBeenCalledTimes(1);expect(track.stop).not.toHaveBeenCalled();reply();expect(hooks.phase).toHaveBeenLastCalledWith('listening');});
 it('idle pause and explicit end close microphone and peer',async()=>{await c.start();reply();await vi.advanceTimersByTimeAsync(61000);expect(track.stop).toHaveBeenCalledTimes(1);expect(peer.close).toHaveBeenCalled();expect(hooks.phase).toHaveBeenLastCalledWith('done');});
 it('forwards distinct rate-limit reasons and stops tracks',async()=>{(fetch as any).mockResolvedValue(new Response(JSON.stringify({ok:false,reason:'app_burst_limited',retryAfterSeconds:60}),{status:429}));await c.start();expect(hooks.error).toHaveBeenCalledWith('app_burst_limited',60);expect(track.stop).toHaveBeenCalled();});
 it('late permission after closing cannot leak a microphone',async()=>{let grant!:(v:any)=>void;(navigator.mediaDevices.getUserMedia as any).mockImplementation(()=>new Promise(r=>{grant=r;}));const promise=c.start();c.dispose();grant({getTracks:()=>[track],getAudioTracks:()=>[track]});await promise;expect(track.stop).toHaveBeenCalledTimes(1);expect(fetch).not.toHaveBeenCalled();});
});

// Optional hint responses must never hijack the microphone state machine.
describe('support response isolation',()=>{
 const hints=()=>dc.send.mock.calls.map((v:any)=>JSON.parse(v[0])).filter((e:any)=>e.response?.metadata?.purpose==='nhk-turn-support-v1');
 const sendHint=(req:any,id='h1')=>{const metadata=req.response.metadata;emit({type:'response.created',response:{id,metadata}});emit({type:'response.done',response:{id,metadata,status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({turnKey:metadata.turnKey,words:['好き','苦手'],starter:'私は…',example:'猫が好きです。'})}]}]}});};
 it('text completion neither starts nor stops the voice turn',async()=>{hooks.support=vi.fn();await c.start();reply();sendHint(hints().at(-1));expect(hooks.support.mock.calls.at(-1)[0].origin).toBe('model');expect(hooks.phase).toHaveBeenLastCalledWith('listening');expect(track.enabled).toBe(true);expect(hooks.heard).not.toHaveBeenCalled();});
 it('sidecar creation before voice completion cannot take its response id',async()=>{hooks.support=vi.fn();await c.start();emit({type:'response.created',response:{id:'voice'}});emit({type:'response.output_audio_transcript.done',response_id:'voice',transcript:'好きですか。'});sendHint(hints().at(-1));expect(track.enabled).toBe(false);emit({type:'response.done',response:{id:'voice',status:'completed'}});emit({type:'output_audio_buffer.stopped',response_id:'voice'});expect(track.enabled).toBe(true);expect(hooks.error).not.toHaveBeenCalled();});
 it('hint failure is optional; microphone continues listening',async()=>{hooks.support=vi.fn();await c.start();reply();const req=hints().at(-1);emit({type:'error',error:{event_id:req.event_id,code:'server_error'}});expect(track.enabled).toBe(true);expect(hooks.error).not.toHaveBeenCalled();});
 it('hiding hints prevents text calls while main audio still works',async()=>{hooks.support=vi.fn();c.setSupportEnabled(false);await c.start();reply();expect(hints()).toHaveLength(0);expect(track.enabled).toBe(true);});
 it('helper audio is bound to the current visible optional example',async()=>{hooks.support=vi.fn();await c.start();reply();sendHint(hints().at(-1));c.help();const req=JSON.parse(dc.send.mock.calls.at(-1)[0]);expect(req.response.output_modalities).toEqual(['audio']);expect(req.response.instructions).toContain('猫が好きです。');expect(req.response.instructions).toContain('actual belief');});
 it('ending ignores pending hint callbacks and releases the microphone',async()=>{hooks.support=vi.fn();await c.start();reply();const req=hints().at(-1);c.end();sendHint(req);expect(track.stop).toHaveBeenCalledTimes(1);expect(hooks.phase).toHaveBeenLastCalledWith('done');});
});
